<?php
/**
 * api/ask_ai.php
 * ---------------------------------------------------------------
 * Handles AI email generation via Google Gemini API
 * ---------------------------------------------------------------
 */

// Prevent PHP deprecation notices/warnings from polluting JSON responses
ini_set('display_errors', '0');
error_reporting(E_ALL);

header('Content-Type: application/json');

if ($_SERVER['REQUEST_METHOD'] !== 'POST') {
    http_response_code(405);
    echo json_encode(['success' => false, 'error' => 'Method not allowed']);
    exit;
}

$prompt = trim($_POST['prompt'] ?? '');

if ($prompt === '') {
    http_response_code(422);
    echo json_encode(['success' => false, 'error' => 'Prompt is required']);
    exit;
}

// 1. Read from environment or parse root .env directly
$apiKey = getenv('GEMINI_API_KEY') ?: ($_ENV['GEMINI_API_KEY'] ?? '');

if (empty($apiKey)) {
    $envPath = dirname(__DIR__) . '/.env';
    if (file_exists($envPath)) {
        $lines = file($envPath, FILE_IGNORE_NEW_LINES | FILE_SKIP_EMPTY_LINES);
        foreach ($lines as $line) {
            $line = trim($line);
            if ($line === '' || str_starts_with($line, '#')) continue;
            if (str_starts_with($line, 'GEMINI_API_KEY=')) {
                $apiKey = trim(substr($line, strlen('GEMINI_API_KEY=')));
                $apiKey = trim($apiKey, "\"'");
                break;
            }
        }
    }
}

if (empty($apiKey)) {
    http_response_code(500);
    echo json_encode([
        'success' => false,
        'error' => 'Gemini API key is not configured. Please check your .env file.'
    ]);
    exit;
}

// 2. Prepare System Instruction
$systemInstruction = "You are an expert, polite, and professional HR assistant for a company in Malaysia. "
    . "Your job is to draft clean, professional, and well-structured workplace emails based on the HR officer's request. "
    . "Rules:\n"
    . "- Always include a clear 'Subject:' line at the top.\n"
    . "- Use standard, professional workplace tone (English or Bahasa Melayu matching the prompt's language).\n"
    . "- Provide placeholder brackets like [Date], [Company Name], or [Department] where specific company details are required.\n"
    . "- Do not output conversational filler or preamble. Output only the email text directly.";

// 3. Gemini REST API Endpoint
$model = "gemini-3.1-flash-lite"; 
$url = "https://generativelanguage.googleapis.com/v1beta/models/{$model}:generateContent?key=" . urlencode($apiKey);

// 4. Construct Payload
$payload = [
    'system_instruction' => [
        'parts' => [
            ['text' => $systemInstruction]
        ]
    ],
    'contents' => [
        [
            'role' => 'user',
            'parts' => [
                ['text' => $prompt]
            ]
        ]
    ],
    'generationConfig' => [
        'temperature' => 0.3,
        'maxOutputTokens' => 1000
    ]
];

// 5. Execute cURL Request
$ch = curl_init($url);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
curl_setopt($ch, CURLOPT_POST, true);
curl_setopt($ch, CURLOPT_HTTPHEADER, [
    'Content-Type: application/json'
]);
curl_setopt($ch, CURLOPT_POSTFIELDS, json_encode($payload));
curl_setopt($ch, CURLOPT_TIMEOUT, 30);
curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);

$responseRaw = curl_exec($ch);
$httpCode = curl_getinfo($ch, CURLINFO_HTTP_CODE);
$curlError = curl_error($ch);

// In PHP 8.0+, curl handles close automatically; in PHP 8.5 curl_close is deprecated
if (PHP_VERSION_ID < 80500 && is_resource($ch)) {
    curl_close($ch);
}

if ($curlError) {
    http_response_code(500);
    echo json_encode([
        'success' => false,
        'error' => "cURL Error: " . $curlError
    ]);
    exit;
}

$response = json_decode($responseRaw, true);

if ($httpCode !== 200) {
    $errorMessage = $response['error']['message'] ?? "Gemini API returned error code {$httpCode}: " . substr($responseRaw, 0, 150);
    http_response_code(500);
    echo json_encode([
        'success' => false,
        'error' => $errorMessage
    ]);
    exit;
}

// 6. Extract Generated Text
$generatedText = $response['candidates'][0]['content']['parts'][0]['text'] ?? '';

if (empty($generatedText)) {
    http_response_code(500);
    echo json_encode([
        'success' => false,
        'error' => 'No content was generated by Gemini.'
    ]);
    exit;
}

echo json_encode([
    'success' => true,
    'email'   => trim($generatedText)
]);